[versions]
agp = "9.0.0"
asmAll = "3.3.1"
cardview = "1.0.0"
cfr = "0.152"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
appcompat = "1.7.1"
kotlinStdlib = "2.3.0"
material = "1.14.0-alpha09"
activity = "1.12.3"
constraintlayout = "2.2.1"
benManes = "0.53.0"
ktfmt = "0.25.0"
multidex = "2.0.1"
preference = "1.2.1"
recyclerview = "1.4.0"
swiperefreshlayout = "1.2.0"
volley = "1.2.1"
mmkv = "2.3.0"

[libraries]
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
asm = { group = "asm", name = "asm-all", version.ref = "asmAll" }
cfr = { group = "org.benf", name = "cfr", version.ref = "cfr" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
mmkv = { group = "com.tencent", name = "mmkv", version.ref = "mmkv" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ktfmt-gradle = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
ben-manes = { id = "com.github.ben-manes.versions", version.ref = "benManes" }